services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mfe_auth
    ports:
      - 3306:3306